spring:
  application:
    name: eureka-discovery-service
server:
  port: 8400
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8400/eureka
    register-with-eureka: false
    fetch-registry: false
